In [3]:
import numpy as np

Splitting is reverse of joining.

Joining merges multiple arrays to a single and splitting aplits one array to multiple.

We use array_split() method to split array. We pass it array to split and number of splits, all as arguments

In [4]:
l1 = [1, 2, 3, 4, 5, 6]
arr = np.array(l1)
print("Original array:")
print(arr)
newarr = np.array_split(arr, 4) # If the array has less elements than required, it will adjust from the end accordingly.
print("Splitted array:")
print(newarr)

Original array:
[1 2 3 4 5 6]
Splitted array:
[array([1, 2]), array([3, 4]), array([5]), array([6])]


 We also have the method split() available but it will not adjust the elements when elements are less in source array for splitting like in example above, array_split() worked properly but split() would fail.

In [10]:
l2 = [1, 2, 3, 4, 5, 6, 7, 8, 9]
arr2 = np.array(l2)
newarr2 = np.split(arr2, 2) # Here, the array has to be exactly divisible by the number of splits, else it will throw an error.
print("Another splitted array:")
print(newarr2)

ValueError: array split does not result in an equal division

**indexing the splitted array**

The return value of the array_split() method is a list containing each of the split as an array.

In [5]:
print(newarr[0]) # Accessing the first list of the splitted array
print(newarr[1]) # Accessing the second list of the splitted array


[1 2]
[3 4]


```python
Splitting 2D arrays
```

splits array to given number of splits but keep aray 2D

In [12]:
arr3 = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr3 = np.array_split(arr3, 10) # Splitting 2D arrays
print("Splitted 2D array:")
print(newarr3)
# print(newarr3[0]) # Accessing the first 2D list of the splitted 2D array
# print(newarr3[9]) # Accessing the second 2D list of the splitted 2D array

Splitted 2D array:
[array([[1, 2]]), array([[3, 4]]), array([[5, 6]]), array([[7, 8]]), array([[ 9, 10]]), array([[11, 12]]), array([], shape=(0, 2), dtype=int64), array([], shape=(0, 2), dtype=int64), array([], shape=(0, 2), dtype=int64), array([], shape=(0, 2), dtype=int64)]
[]


you can specify which axis you want to do the split around.

ie. to split along column, we use axis=1

how it will split.? takes the elements column wise ie. 1st element from 1st column of all rows

In [16]:
arr4 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr4 = np.array_split(arr4, 6, axis=1) # Splitting 2D arrays along columns
print("Splitted 2D array along columns:")
# print(newarr4)
print(newarr4[0]) # Accessing the first 2D list of the splitted 2D array
print(newarr4[1]) # Accessing the second 2D list of the splitted 2D array
print(newarr4[2])
print(newarr4[3])
print(newarr4[4])


Splitted 2D array along columns:
[[ 1]
 [ 4]
 [ 7]
 [10]
 [13]
 [16]]
[[ 2]
 [ 5]
 [ 8]
 [11]
 [14]
 [17]]
[[ 3]
 [ 6]
 [ 9]
 [12]
 [15]
 [18]]
[]
[]


alternate of column wise splitting of using axis = 1 is hsplit()

but raise error when given splits are not possible from aray

In [22]:
arr5 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr5 = np.hsplit(arr5, 3) 
print("Splitted 2D array along columns using hsplit():")
print(newarr5)
print(newarr5[0])
print(newarr5[1])
print(newarr5[2])

Splitted 2D array along columns using hsplit():
[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]
[[ 1]
 [ 4]
 [ 7]
 [10]
 [13]
 [16]]
[[ 2]
 [ 5]
 [ 8]
 [11]
 [14]
 [17]]
[[ 3]
 [ 6]
 [ 9]
 [12]
 [15]
 [18]]


similarly we ca split 3 dimensional and n dimensional arrays

3D arrays have alternate of hstack() and dstack() methods, hsplit() and dsplit()

In [36]:
arr6 = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])
print(arr6.shape) # checkinh if it is 3D array
# newarr6 = np.dsplit(arr6, 3)
# newarr6 = np.hsplit(arr6, 3)
newarr6 = np.vsplit(arr6, 2)
# print(newarr6)
print(newarr6[0])
print(newarr6[1])
# print(newarr6[2])

(2, 3, 3)
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[10 11 12]
  [13 14 15]
  [16 17 18]]]
