In [1]:
import numpy as np

**Sorting means putting elements in arranged manner.**

Sequence could be any numeric, alphabetical, ascending or descending

**numpy array has a function sort() for this operation.**
**It makes a copy of array leaving original one unchanged**

In [3]:
arr1 = np.array([4, 1, 9, 5, 2, 6, 4, 0])
print("Original array:")
print(arr1)

print("\nSorted array:")
print(np.sort(arr1))

print("\nOriginal array after sorting:")
print(arr1)

Original array:
[4 1 9 5 2 6 4 0]

Sorted array:
[0 1 2 4 4 5 6 9]

Original array after sorting:
[4 1 9 5 2 6 4 0]


**We can also sort arrays of any data type**

In [4]:
arr2 = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr2))

['apple' 'banana' 'cherry']


In [5]:
arr3 = np.array([True, False, True])
print(np.sort(arr3))

[False  True  True]


**Sorting a 2-D Array**

In [ ]:
arr = np.array([[3, 2, 4], [5, 0, 1]])
# print(np.sort(arr)) # sorts each . same as axis=1
# print(np.sort(arr, axis=0)) # sorts each column
# print(np.sort(arr, axis=None)) # flattens the array and sorts it

[[2 3 4]
 [0 1 5]]


**checking 3D arrays**

In [16]:
arr3 = np.array([[[5, 1], [3, 9]], [[1, 7], [6, 4]]])
# print(arr3.shape)
print(np.sort(arr3, axis=0)) # sorts along the first axis. take all elements, sort them and put them back in their respective places

# print(np.sort(arr3, axis=1)) # sorts along the second axis. column wise sorting in each block

# print(np.sort(arr3, axis=2)) # sorts along the third axis. row wise sorting in each block

# print(np.sort(arr3, axis=None)) # flattens the array and sorts it

[[[1 1]
  [3 4]]

 [[5 7]
  [6 9]]]
