In [1]:
import numpy as np

**Getting some elements out of an existing array and creating a new array out of them is called filtering.**

In NumPy, you filter an array using a boolean index list.

**A boolean index list is a list of booleans corresponding to indexes in the array.**

If the value at an index is True that element is contained in the filtered array, if the value at that index is False that element is excluded from the filtered array.

In [4]:
arr = np.array([1, 2, 3, 4, 5, 6])
f_arr = [False, True, False, True, False, True]

# print(arr[f_arr])  

newarr_f = arr[f_arr]
print(newarr_f)


[2 4 6]


**Make a filtered array containing only numbers > 50**

In [5]:
arr1 = np.array([41, 42, 43, 44, 48, 50, 60, 67, 45, 89, 90])

f_arr1 = []

for element in arr1:
    if element > 50:
        f_arr1.append(True)
    else:
        f_arr1.append(False)
newarr1_f = arr1[f_arr1]
print(newarr1_f)

[60 67 89 90]


**there are more precise ways to do all these filterations**

In [6]:
f_ar2 = arr1 > 50
newarr2_f = arr1[f_ar2]
print(newarr2_f)

[60 67 89 90]


In [7]:
f_arr2 = arr1%2 == 0
newarr3_f = arr1[f_arr2]
print(newarr3_f)

[42 44 48 50 60 90]
