In [1]:
from numpy import random

**What are random numbers?**

Random number doesn't mean a new number every time but it means a numbers that cannot be predicted logically.

**True Randoms** are numbers used in security purposes like encryption.

We will be practicing **pseudo randoms** that are generated through some a generation algorithm.

**Generating random integer through randint()**

It takes size as argument.

In [4]:
r1 = random.randint(50)
print(r1)

31


**Generating random float through rand()**

It returns a float b/w 0 and 1.

In [8]:
r2 = random.rand()
print(r2)

0.19242251472822014


**Generating random array**

rand() and randint() methods take array shape as arguments

In [14]:
r3 = random.randint(100, size=(5))
print(r3)

[83 57 93 91 74]


In [16]:
r4 = random.rand(5)
print(r4)

[0.67285048 0.25944206 0.44422304 0.42709377 0.59436626]


In [17]:
print(random.randint(100, size=(3, 4)))

[[63 36 61 46]
 [55 67 42 65]
 [43 40 60 67]]


In [18]:
print(random.randint(100, size=(2, 3, 4)))

[[[76 75  1 42]
  [42 46 12 66]
  [ 2 90 50 60]]

 [[ 1 30 90 82]
  [ 0 23 17 87]
  [95 95 92 50]]]


In [20]:
print(random.rand(3, 4))

[[0.67830524 0.24716432 0.76944837 0.99942596]
 [0.09705788 0.03041591 0.62445611 0.92479074]
 [0.3558208  0.13772058 0.10514156 0.08400491]]


In [22]:
print(random.rand(2, 3, 4))

[[[0.03408615 0.77861597 0.93166714 0.32243089]
  [0.71723294 0.48525029 0.59859052 0.5568512 ]
  [0.18237722 0.22603759 0.58015364 0.07518147]]

 [[0.56545389 0.15234167 0.57111901 0.17621011]
  [0.14800634 0.37968723 0.91950628 0.00674736]
  [0.66774397 0.28642917 0.26628066 0.89219438]]]


**We can also genarate randoms from an array**

In [29]:
r5 = random.choice([5, 2, 7, 4, 9])
print(r5)

9


In [32]:
r6 = random.choice([5 ,8], size=(3, 5))
print(r6)

[[8 5 8 8 5]
 [5 8 8 8 5]
 [8 5 5 8 5]]
