In [1]:
import numpy as np

**Data Distribution**

Data distribution is a list of all possible values and how offen each value occurs.

**Random Distribution**

is a set of random numbers that follow a certain probability density function.

**probability density function**  describes a continuous probability ie. probability of all values in array

In [5]:
r1 = np.random.choice([2, 5, 9, 1], p=[0.2, 0.3, 0.4, 0.1], size=(5, 5, 10))
print(r1)

[[[9 9 2 5 9 2 9 2 5 9]
  [5 9 5 1 5 9 5 9 9 5]
  [5 5 2 9 9 9 9 9 5 9]
  [9 1 5 9 2 5 9 2 2 9]
  [5 9 9 5 9 9 2 9 9 9]]

 [[5 9 9 1 1 1 9 9 1 9]
  [9 1 9 9 1 5 5 5 5 2]
  [9 2 5 9 2 5 9 9 5 5]
  [2 2 9 5 9 9 5 1 9 1]
  [2 9 5 5 5 9 5 9 5 2]]

 [[1 1 5 9 1 2 9 9 5 5]
  [9 9 9 5 9 1 9 1 1 9]
  [2 5 2 5 5 5 2 9 1 5]
  [2 5 9 5 2 9 9 2 5 9]
  [9 2 1 1 2 1 2 9 9 2]]

 [[5 1 9 9 1 5 9 2 2 2]
  [9 9 2 5 9 5 9 1 1 5]
  [9 9 2 9 5 5 9 5 2 5]
  [5 2 9 9 5 1 1 1 2 2]
  [5 2 9 5 9 9 5 5 5 5]]

 [[9 9 2 5 9 9 5 5 9 9]
  [5 2 5 2 9 9 9 9 1 2]
  [9 9 9 1 2 9 5 5 2 9]
  [1 2 2 9 5 9 5 5 9 1]
  [9 5 5 9 9 2 9 9 9 2]]]


We can generate random numbers based on defined probabilities using the choice() method of the random module.

The choice() method allows us to specify the probability for each value.

The probability is set by a number between 0 and 1, where 0 means that the value will never occur and 1 means that the value will always occur.

**The sum of all probability numbers should be 1.**