In [1]:
import numpy as np

In [3]:
# if you want to change elements of array, 1st make copy of it to keep original array as it is.
arr = np.array([1, 2, 3, 4, 5])
arr2 = arr.copy()
arr[0] = 11
print(arr)
print(arr2)

[11  2  3  4  5]
[1 2 3 4 5]


In [5]:
print(arr2.shape)

(5,)


In [7]:
# view is opposite to copy function. it also made a copy/view but changes in any array original or copy changes both arrays
arr3 = arr2.view()
arr2[1] = 22
print(arr2, arr3)
arr3[3] = 34
print(arr2, arr3)

[ 1 22  3 34  5] [ 1 22  3 34  5]
[ 1 22  3 34  5] [ 1 22  3 34  5]


In [8]:
print(np.shape(arr3))
print(np.size(arr3))

(5,)
5


In [9]:
print(arr.shape)

(5,)


In [10]:
print(arr2.size)

5


In [11]:
# numpy copy() owns data and view() doesn't own data. None is returned for owning data, otherwise array is returned.
x = arr.copy()
y = arr.view()
print(x.base)
print(y.base)

None
[11  2  3  4  5]
