In [1]:
import numpy as np

In [6]:
arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
# shape of an array is number of elements in each dimension
new_arr = arr1.reshape(6, 2)  # 6 dimensions/rows and 2 columns in each row.
print(new_arr)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [8]:
new_arr2 = arr1.reshape(2, 3, 2)
print(new_arr2) # reshaped to 3D array, 2 blocks, 3 rows in each block and 2 columns in each row.

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [9]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr.reshape(2, 4).base) # view: returns original array

[1 2 3 4 5 6 7 8]


In [11]:
new_arr3 = arr.reshape(2, 2, -1) # we are allowed to give one dimension wrong, numpy will calculate it by itself
print(new_arr3)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [20]:
# Flattening array means converting a multidimensional array into a 1D array.
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
new_arr4 = arr2.reshape(-1)
print(new_arr4)

[1 2 3 4 5 6]
