In [2]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5]) # 1D array
for i in arr:
    print(i)

1
2
3
4
5


In [3]:
arr = np.array([[1, 2, 3], [4, 5, 6]]) # 2D array
for i in arr:
    print(i)

[1 2 3]
[4 5 6]


In [4]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
for i in arr:
    for j in i:
        print(j)


1
2
3
4
5
6


In [6]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for i in arr:
    print(i)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [12]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
  for y in x:
    for z in y:
      print(z)
print(arr.shape)
print(arr.size)

1
2
3
4
5
6
7
8
9
10
11
12
(2, 2, 3)
12


In [13]:
# nditer() function of numpy help in iterating n-dimensional arrays
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12


In [15]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
    print(x)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
np.bytes_(b'4')
np.bytes_(b'5')
np.bytes_(b'6')
np.bytes_(b'7')
np.bytes_(b'8')
np.bytes_(b'9')
np.bytes_(b'10')
np.bytes_(b'11')
np.bytes_(b'12')


In [22]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]): # both blocks, all rows, but elements with step of 2
  print(x)

1
3
5
7


In [24]:
arr = np.array([1, 2, 3])
for index, x in np.ndenumerate(arr):
    print(f"index: {index} -> {x}")

index: (0,) -> 1
index: (1,) -> 2
index: (2,) -> 3


In [25]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
