In [1]:
import numpy as np

In [4]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.concatenate((arr1, arr2))
print(arr3)

[1 2 3 4 5 6]


In [9]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

# by default axis 0 hota ha. 0 ka mtlb ha k row wise concatenate kro means 1st array k nichay second ko rkh lo
# 1 ka mtlb ha column wise, 1st array ki 1st row and second array ki 1st row inhay same row ma lay ao columns increase kr lo
# 2D array ma 0 or 1 e use hotay hayn

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [14]:
# 3D arrays ma axis = 2 b use hota hay
arr1 = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

arr2 = np.array([
    [[9, 10], [11, 12]],
    [[13, 14], [15, 16]]
])

arr = np.concatenate((arr1, arr2), axis=0)
print(arr)
print(arr.shape)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]]
(4, 2, 2)
