In [1]:
import numpy as np

**Simple Arithmetic**

You could use arithmetic operators + - * / directly between NumPy arrays, but this section discusses an extension of the same where we have functions that can take any array-like objects e.g. lists, tuples etc. and perform arithmetic conditionally.

**Arithmetic Conditionally**: means that we can define conditions where the arithmetic operation should happen.

All of the discussed arithmetic functions take a **where** parameter in which we can specify that condition.

In [2]:
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.add(arr1, arr2)

print(newarr)

[30 32 34 36 38 40]


In [3]:
# Subtract the values in arr2 from the values in arr1:

newarr2 = np.subtract(arr1, arr2)
print(newarr2)

[-10 -10 -10 -10 -10 -10]


In [4]:
# Multiply

newarr3 = np.multiply(arr1, arr2)
print(newarr3)

[200 231 264 299 336 375]


In [ ]:
# divide values of arr1 from 2
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 10, 8, 2, 33])

newarr4 = np.divide(arr1, arr2)
print(newarr4)

[ 3.33333333  4.          3.          5.         25.          1.81818182]


In [ ]:
#  POWER: Raise the valules in arr1 to the power of values in arr2:
newarr5 = np.power(arr1, arr2, dtype=object)
print(newarr5)

# numpy datatype ka size int 32 ya int64 e ho skta ha jb k python unlimeted sized values ko b handle kr sktahay is liya dtype=object k ilava agr run kro to 60**33 0 output dayta hay


[1000 3200000 590490000000000 6553600000000 2500
 47751966659678405306351616000000000000000000000000000000000]


Both the mod() and the remainder() functions return the remainder of the values in the first array corresponding to the values in the second array, and return the results in a new array.

In [10]:
# newarr6 = np.mod(arr1, arr2)
newarr6 = np.remainder(arr1, arr2)
print(newarr6)

[ 1  0  0  0  0 27]


The divmod() function return both the quotient and the mod. The return value is two arrays, the first array contains the quotient and second array contains the mod.

In [14]:
newarr7 = np.divmod(arr1, arr2)
print(f"Quotients:  {newarr7[0]}")
print(f"Remainders: {newarr7[1]}")

Quotients:  [ 3  4  3  5 25  1]
Remainders: [ 1  0  0  0  0 27]


Both the absolute() and the abs() functions do the same absolute operation element-wise but we should use absolute() to avoid confusion with python's inbuilt math.abs()

In [15]:
arr = np.array([-1, -2, 1, 2, 3, -4])
newarr8 = np.absolute(arr)
print(newarr8)

[1 2 1 2 3 4]
