In [1]:
import numpy as np

There are primarily five ways of rounding off decimals in NumPy:

**-->truncation**
    
**-->fix**
    
**-->rounding**
    
**-->floor**
    
**-->ceil**

**Truncation**

Remove the decimals, and return the float number closest to zero. Use the **trunc()** and **fix()** functions.

In [ ]:
arr1 = np.array([-3.1666, 3.6667])

print(np.trunc(arr1))

print(np.fix(arr1))


[-3.  3.]
[-3.  3.]


**Rounding**

The **around()** function increments preceding digit or decimal by 1 if >=5 else do nothing.

E.g. round off to 1 decimal point, 3.16666 is 3.2

In [15]:
print(np.around([3.1666], 1))
print(np.around([3.155], 1))
print(np.around([3.144], 1))

[3.2]
[3.2]
[3.1]


The **floor()** function rounds off decimal to nearest lower integer.

In [17]:
print(np.floor([3.96, 3.94, 3.43, 3.46]))

[3. 3. 3. 3.]


The **ceil()** function rounds off decimal to nearest upper integer.

In [19]:
print(np.ceil([3.96, 3.94, 3.43, 3.46]))
print(np.around([3.96, 3.94, 3.43, 3.46]))

[4. 4. 4. 4.]
[4. 4. 3. 3.]
