In [1]:
import numpy as np

**Logs**

NumPy provides functions to perform log at the base 2, e and 10.

We will also explore how we can take log for any base by creating a custom ufunc.

All of the log functions will place -inf or inf in the elements if the log can not be computed.

**Log at Base 2**

In [4]:
ar = np.arange(1, 10) # return array of integers from 1 to 9
print(ar)
print(np.log2(ar))

[1 2 3 4 5 6 7 8 9]
[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]


**Log at Base 10**

In [5]:
print(ar)
print(np.log10(ar))

[1 2 3 4 5 6 7 8 9]
[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]


**Natural Log, or Log at Base e**

In [6]:
print(ar)
print(np.log(ar))

[1 2 3 4 5 6 7 8 9]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]


**Log at Any Base**

NumPy does not provide any function to take log at any base, so we can use the frompyfunc() function along with inbuilt function math.log() with two input parameters and one output parameter:

In [9]:
from math import log

nplog = np.frompyfunc(log, 2, 1)

print(nplog(5, 5))

1.0
