In [1]:
import numpy as np

**To find the product of the elements in an array, use the prod() function**

In [ ]:
# Find the product of the elements of this array:
arr = np.array([1, 2, 3, 4])

x = np.prod(arr) # 1*2*3*4
print(x)

24


In [ ]:
arr1 = np.array([1, 2, 3, 4])

x = np.prod([arr, arr1]) # 1*2*3*4*1*2*3*4

print(x)

576


**If you specify axis=1, NumPy will return the product of each array.**

In [ ]:
print(np.prod([arr, arr1], axis=1))

[ 1  4  9 16]


**Cummulative Product**

Cummulative product means taking the product partially.

E.g. The partial product of [1, 2, 3, 4] is [1, 1 * 2, 1* 2* 3, 1* 2* 3* 4] = [1, 2, 6, 24]

Perfom partial product with the cumprod() function.

In [12]:
print(np.cumprod([arr1]))
print(np.cumprod([arr1, arr]))
print(np.cumprod([arr1, arr], axis=1))

[ 1  2  6 24]
[  1   2   6  24  24  48 144 576]
[[ 1  2  6 24]
 [ 1  2  6 24]]
