In [1]:
import numpy as np

NumPy provides the ufuncs sin(), cos() and tan() that take values in radians and produce the corresponding sin, cos and tan values.

In [3]:
# finding sine value of pi/2

x = np.sin(np.pi/2)
print(x)

1.0


In [6]:
arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])

y = np.sin(arr)

print(y)

[1.         0.8660254  0.70710678 0.58778525]


By default all of the trigonometric functions take radians as parameters but we can convert radians to degrees and vice versa as well in NumPy.

**Note:** radians values are pi/180 * degree_values.

In [ ]:
# Convert all of the values in following array arr to radians:

arr = np.array([90, 180, 270, 360])

a1 = np.deg2rad(arr)
print(a1)

[1.57079633 3.14159265 4.71238898 6.28318531]


In [8]:
# Convert all of the values in following array arr to degrees:

arr = np.array([np.pi/2, np.pi, 1.5*np.pi, 2*np.pi])

a2 = np.rad2deg(arr)

print(a2)

[ 90. 180. 270. 360.]


Finding angles from values of sine, cos, tan. E.g. sin, cos and tan inverse (arcsin, arccos, arctan).

NumPy provides ufuncs arcsin(), arccos() and arctan() that produce radian values for corresponding sin, cos and tan values given.

In [9]:
x = np.arcsin(1.0)

print(x)

1.5707963267948966


In [10]:
arr = np.array([1, -1, 0.1])

x = np.arcsin(arr)

print(x)

[ 1.57079633 -1.57079633  0.10016742]


**Finding hypotenues using pythagoras theorem in NumPy.**

NumPy provides the hypot() function that takes the base and perpendicular values and produces hypotenues based on pythagoras theorem.

In [11]:
base = 3
perp = 4

hyp = np.hypot(base, perp)

print(hyp)

5.0
